### ISSUE TITLE
__init__() got an unexpected keyword argument 'qk_scale'

### ISSUE THREAD

**Issue by zlgenuine** [facebookresearch/mae#58]
sys.path.append('..')
import models_mae
dir(models_mae.Block)

The module has been successfully imported. But there is an error happened to Block Class. 
Use it in jupyter notebook. 
Any idea of it?

**Comment by daisukelab** [comment]
Hi @zlgenuine, I think you can check the timm version.

**Comment by Z-FL** [comment]
I ran into the same problem, my version is 0.5.4, what version should I use?

**Comment by daisukelab** [comment]
> This repo is based on [timm==0.3.2](https://github.com/rwightman/pytorch-image-models), for which a https://github.com/rwightman/pytorch-image-models/issues/420#issuecomment-776459842 is needed to work with PyTorch 1.8.1+.

**Comment by endernewton** [comment]
Thanks @daisukelab! The latest version of `timm` may not be compatible.

**Comment by zlgenuine** [comment]
> Hi @zlgenuine, I think you can check the timm version.

Do you have such a link that I can download， many  thanks.

**Comment by zlgenuine** [comment]
> Hi @zlgenuine, I think you can check the timm version.

Thanks

**Comment by xml94** [comment]
Details:
1) install timm==0.3.2: `pip install timm==0.3.2`
2) go to timm/models/layers/helpers.py and add:
```
import torch
TORCH_MAJOR = int(torch.__version__.split('.')[0])
TORCH_MINOR = int(torch.__version__.split('.')[1])

if TORCH_MAJOR == 1 and TORCH_MINOR < 8:
    from torch._six import container_abcs
else:
    import collections.abc as container_abcs
```

if you are using conda, you can use `sudo find / -name timm` to find the place of timm you installed.

**Comment by ronboxer17** [comment]
In my case what's worked is to install timm==0.4.12 and delete this variable('qk_scale') from 'models_mae.py'.
It appears twice.

**Comment by ffhibnese** [comment]
You need to do nothing but `pip install timm-0.4.12`

**Comment by aiguoli** [comment]
You can just remove `qk_scale` as follow, it will work fine

https://github.com/huggingface/pytorch-image-models/pull/1091#issuecomment-1014850194

**Comment by benlin1211** [comment]
> You can just remove `qk_scale` as follow, it will work fine
> 
> [huggingface/pytorch-image-models#1091 (comment)](https://github.com/huggingface/pytorch-image-models/pull/1091#issuecomment-1014850194)

Very helpful! Thank you.
